### ISSUE TITLE
Bug: since commit 0126ac0 chosing of a colorscheme specific lualine theme is not possible anymore - it's always 'auto'

### ISSUE THREAD

**Issue by wimstefan** [shadmansaleh/lualine.nvim#12]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
I've tested this behaviour with  [material.nvim](https://github.com/marko-cerovac/material.nvim) since this is the only colorscheme installed which has offered both a theme built in lualine (`material`) and in the specific colorscheme (`material-nvim`).

1. set the colorscheme as described in the [documentation of material.nvim](https://github.com/marko-cerovac/material.nvim#-usage)  with
``` lua
require('material').set()
```
2. set the lualine theme as suggested in the documentation
```lua
require('lualine').setup{options = {theme = 'material-nvim'}}
```
### Actual behaviour
The lualine theme is set to "auto"
### Expected behaviour
The lualine theme should be set according to the settings - in this case `material-nvim`

**Comment by shadmansaleh** [comment]
Sorry can't reproduce it.
It loads `metarial-nvim` correctly for me . Can you share your lualine config ? Do you get any notices about theme faliure ?

**Comment by wimstefan** [comment]
Thank you for the fast response!
Unfortunately I can't get your `test.lua` working so I can't execute the test you're asking me to do :/

But I can give you the config I'm using:
<details>
<summary>lualine config</summary>

```lua
  use {
    'shadmansaleh/lualine.nvim',
    -- commit = 'd3600399',
    event = {'BufEnter', 'ColorScheme', 'WinEnter'},
    requires = {'kyazdani42/nvim-web-devicons'},
    config = function()
      if vim.fn.filereadable(vim.fn.expand('$HOME/.config/colours/nvim_theme.lua')) == 1 then
        vim.api.nvim_command[[luafile $HOME/.config/colours/nvim_theme.lua]]
      else
        vim.api.nvim_command[[colorscheme desert]]
      end
      local get_modified = function()
        return '%m' or ''
      end
      local get_readonly = function()
        if not vim.bo.readonly then
          return ''
        end
        return '[RO]'
      end
      local get_session = function()
        if not vim.g.loaded_obsession then
          return ''
        end
        return '%{ObsessionStatus("\\\\o/", "_o_")}'
      end
      local get_spell = function()
        if not vim.wo.spell then
          return ''
        end
        return '[SP]'
      end
      local get_path = function()
        return '%F'
      end
      local diff_source = function()
        local gitsigns = vim.b.gitsigns_status_dict
        if gitsigns then
          return {added = gitsigns.added, modified = gitsigns.changed, removed = gitsigns.removed}
        end
      end
      local minimal_extension = {
        sections = {
          lualine_a = {get_path},
          lualine_b = {},
          lualine_c = {},
          lualine_x = {},
          lualine_y = {'location', 'progress'},
          lualine_z = {'filetype'},
        },
        filetypes = {'help', 'packer', 'qf'}
      }

      require('lualine').setup {
        options = {
          icons_enabled = true,
          section_separators = {'┃', '┃'},
          component_separators = {''},
        },
        sections = {
          lualine_a = {'mode'},
          lualine_b = {'location', 'progress'},
          lualine_c = {
            {get_path},
            {
              get_readonly,
              padding = 0,
              color = {fg = 'grey'},
            },
            {
              get_modified,
              padding = 0,
              color = {fg = 'red'},
            },
            {
              get_spell,
              padding = 1,
              color = {fg = 'brown'},
            },
            {
              get_session,
              padding = 1,
              color = {fg = 'yellow'},
            },
          },
          lualine_x = {
            function() return require('lsp-status').status() end,
            {
              'diagnostics',
              sources = {'nvim_lsp'},
              color_warn = {fg = 'orange'},
              symbols = {
                error = ' ' .. vim.trim(vim.fn.sign_getdefined('LspDiagnosticsSignError')[1].text) .. ' ',
                warn = ' ' .. vim.trim(vim.fn.sign_getdefined('LspDiagnosticsSignWarning')[1].text) .. ' ',
                info = ' ' .. vim.trim(vim.fn.sign_getdefined('LspDiagnosticsSignInformation')[1].text) .. ' ',
                hint = ' ' .. vim.trim(vim.fn.sign_getdefined('LspDiagnosticsSignHint')[1].text) .. ' '
              }
            },
          },
          lualine_y = {
            {
              'diff',
              source = diff_source,
              symbols = { added = '  ', modified = '  ', removed = '  ' },
            },
            'branch'
          },
          lualine_z = {'filetype'},
        },
        inactive_sections = {
          lualine_a = {get_path},
          lualine_b = {},
          lualine_c = {},
          lualine_x = {},
          lualine_y = {'location'},
          lualine_z = {'filetype'},
        },
        extensions = {'fugitive', minimal_extension, 'nvim-tree'},
      }
    end
  }
```

</details>
<details>
<summary>nvim_theme.lua</summary>

```lua
vim.o.background = 'dark'

local set_theme = function(theme)
  if theme == 'material' then
    if vim.o.background == 'dark' then
      vim.g.material_style = 'palenight'
    else
      vim.g.material_style = 'lighter'
    end
    require('material').set()
    require('lualine').setup{options = {theme = 'material-nvim'}}
  elseif theme == 'tokyonight' then
    vim.api.nvim_command('colorscheme tokyonight')
    require('lualine').setup{options = {theme = 'tokyonight'}}
  elseif theme == 'nordbuddy' then
    vim.api.nvim_command('colorscheme nordbuddy')
  elseif theme == 'edge' then
    vim.api.nvim_command('colorscheme edge')
  elseif theme == 'artesanal' then
    vim.api.nvim_command('colorscheme artesanal')
  else
    vim.api.nvim_command('colorscheme desert')
  end
end

if vim.o.background == 'dark' then
  set_theme('material')
else
  set_theme('material')
end
```

</details>

**Comment by shadmansaleh** [comment]
Fixed in https://github.com/shadmansaleh/lualine.nvim/commit/bdc3073d318a68aed281eb806d03418aa79eddf1

**Comment by aserowy** [comment]
Heho,

switched to your fork recently. Im still getting this issue. Changes like setting separators in https://github.com/aserowy/NeoCode/blob/main/lua/status/plugin_lualine.lua have an effect. But changing the theme option (even setting it hard to auto or other existing themes) will result in the default. I dont get any errors/warnings.

How can i help to narrow it down?

Kind regards

**Comment by shadmansaleh** [comment]
Sorry it's not possible for me to go through dotfiles to find issue . If you think it's a bug in lualine please try to provide a minimal reproduction [this script](https://gist.github.com/shadmansaleh/3aca29632e9a77a632705b62617c9dac) help you with that.

For isolating the theme issue first check if you're providing a valid theme to lualines setup.

See if command like
```lua
:lua require"lualine".setup{options={theme='nord'}}
```
changes the theme.
If you're providing a theme name check if there are errors while requireing that theme
```lua
:lua require'lualine.themes.nord'
```

lualine will fallback to `auto` if there was some error loading the theme .

I'd like to add some logging for errors so they aren't completely silent .

**Comment by aserowy** [comment]
Coming to say sorry, everything works as expected. My configuration shredded true color (without me noticing). Thus, colors looked off.

Sry for wasted time :*
